version: '3.6'

services:
  web:
    build: ./pollsapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pollsapi/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.txt
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgresql_database_name
      - POSTGRES_USER=postgresql_user
      - POSTGRES_PASSWORD=postgresql_password

volumes:
  postgres_data: