# Generated by Django 3.1.7 on 2021-03-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210310_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='answer',
            new_name='vote_answers',
        ),
    ]
