# Generated by Django 3.1.7 on 2021-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210310_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiply', 'Multiply'), ('text', 'Text')], default='single', max_length=10),
        ),
    ]
