# Generated by Django 3.1.7 on 2021-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='custom_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_answers',
            field=models.ManyToManyField(blank=True, related_name='vote_answers', to='polls.Answer'),
        ),
    ]
