# Generated by Django 3.1.7 on 2021-03-10 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210310_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000000), django.core.validators.MaxValueValidator(9000000000000000000)]),
        ),
    ]
